-- Active: 1790759351402@@127.0.0.1@5432
-- Active: 1790759351402@@127.0.0.1@5432
/*const MyTasks = [
    { id: 0, complété: false, titre: "monter" },
    { id: 1, complété: false, titre: "up" },
    { id: 2, complété: false, titre: "down" },
    { id: 3, complété: false, titre: "boom" },
    { id: 4, complété: false, titre: "bam" }
];*/

CREATE TABLE tasks (
    id_task  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_task  BOOLEAN NOT NULL DEFAULT FALSE,
    title_task     VARCHAR(100) NOT NULL
);

INSERT INTO tasks (status_task, title_task) VALUES
    (FALSE, 'ranger'),
    (FALSE, 'nettoyer'),
    (FALSE, 'dormir')