-- Active: 1790759351402@@127.0.0.1@5432


CREATE TABLE IF NOT EXISTS tasks (
    id_task  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_task  BOOLEAN NOT NULL DEFAULT FALSE,
    title_task     VARCHAR(100) NOT NULL
);

INSERT INTO tasks (status_task, title_task) VALUES
    (FALSE, 'ranger'),
    (FALSE, 'nettoyer'),
    (FALSE, 'dormir')