-- Active: 1790759351402@@127.0.0.1@5432


CREATE TABLE IF NOT EXISTS tasks (
    id_task  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_task  BOOLEAN NOT NULL DEFAULT FALSE,
    title_task     VARCHAR(255) NOT NULL,
    assignee  VARCHAR(50)
);

INSERT INTO tasks (status_task, title_task, assignee) VALUES
    (FALSE, 'Déployer site 1', 'Toto'),
    (TRUE, 'Modifier CSS site 2', 'Titi'),
    (FALSE, 'Vérifier sécurité', 'Tata');

